PROG	= ft_display_file
CFLAGS	= -Wall -Wextra -Werror
SOURCES	= ft_display_file.c ft_putchar.c ft_putchar2.c ft_putstr.c ft_putstr2.c

all:
	gcc -c $(CFLAGS) $(SOURCES)
	gcc *.o -o $(PROG)

clean:
	rm *.o

fclean: clean
	rm $(PROG)
